version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8081:8080"
    volumes:
      - ./:/app

  postgres:
    container_name: postgres
    image: postgres:13.3
    restart: always
    environment:
        POSTGRES_USERNAME: "postgres"
        POSTGRES_PASSWORD: "test123"
        POSTGRES_DB: "test_db"
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
